name: Build and Release

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'
    
    - name: Download dependencies
      run: |
        go mod tidy
        go mod download
    
    - name: Run checks
      run: make check
    
    - name: Build
      run: make build

  build:
    needs: test
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'
    
    - name: Download dependencies
      run: |
        go mod tidy
        go mod download
    
    - name: Build Linux AMD64
      run: |
        mkdir -p dist
        CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags="-s -w" -o dist/gosecret-linux-amd64
    
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: gosecret-linux-amd64
        path: dist/gosecret-linux-amd64
        retention-days: 30
    
    - name: Update Development Release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: dev
        name: Development Build
        files: dist/gosecret-linux-amd64
        draft: false
        prerelease: true
        body: |
          Latest development build from commit ${{ github.sha }}
          
          Built from: ${{ github.ref_name }}
          Commit: ${{ github.event.head_commit.message }}